### ISSUE TITLE
Setup Connection to Device

### ISSUE THREAD

**Issue by DanielTongAwesome** [DanielTongAwesome/MindWave_Project#1]
Check the following repo:
https://github.com/Rhuax/Mindwave-brainwaves-reader

1. use the NeuroPy.py to test the connection
2. Do some basic operation to the data

**Comment by rogerluo1995** [comment]
## Device Reading Setup 
This assumes that you have all the packages installed properly. If not, errors will pop out to let you what are missing. 
### Step 0 Manage the Connection to the Device
- Install the Bluetooth Device Manager, Search, and Connect to the MindWave Device (using its MAC address):  http://manpages.ubuntu.com/manpages/bionic/man1/bt-device.1.html
- Bond the MAC address to the Serial Port: https://askubuntu.com/questions/1025080/unable-to-create-dev-rfcomm-port

### Step 1 `main.py`
- Specify the Serial port that the program is going to be connected to: `record = NeuroPy("/dev/rfcomm0", person_name=person_name, task_name=task_name, task_duration=task_duration)` , where `/dev/refcomm0` should be the port you need

### Step 2 `NeuroPy.py`
- Modify line 74 from ` while i < payloadLength:` to ` while i < payloadLength-1:`

### Step 3 Run `main.py`
- The data recording will be saved in `records` folder for plotting
